import { authAPI } from "../../api/auth.js";

let state = {
  data: [],
  currentPage: 1,
  pageSize: 10,
  searchTerm: "",
};

export function getHistoryComponent() {
  return `
          <!-- Table Controls -->
          <div class="table-controls">
            <div class="show-entries">
              <label for="show-entries">Show</label>
              <select id="show-entries">
                <option value="10">10</option>
                <option value="25">25</option>
                <option value="50">50</option>
                <option value="100">100</option>
              </select>
              <span>data</span>
            </div>
            <div class="search-box">
              <input type="text" id="search-input" placeholder="Search" />
            </div>
          </div>

          <!-- Data Table -->
          <div class="data-table-container">
            <table>
              <thead>
                <tr>
                  <th>No</th>
                  <th>Nama Kegiatan</th>
                  <th>Kategori</th>
                  <th>Tingkat Kompetisi</th>
                  <th>Tanggal</th>
                  <th>Skor AI</th>
                  <th>Tingkat</th>
                  <th>Status Validasi</th>
                </tr>
              </thead>
              <tbody id="history-table-body">
                <tr><td colspan="9" style="text-align:center;">Loading...</td></tr>
              </tbody>
            </table>
          </div>

          <!-- Pagination -->
          <div class="pagination" id="pagination-controls">
            <!-- Generated by JS -->
          </div>
  `;
}

export async function initHistoryComponent() {
  const tableBody = document.getElementById("history-table-body");
  const showEntriesSelect = document.getElementById("show-entries");
  const searchInput = document.getElementById("search-input");
  const paginationControls = document.getElementById("pagination-controls");

  if (!tableBody || !showEntriesSelect || !searchInput || !paginationControls)
    return;

  // Event Listeners
  showEntriesSelect.addEventListener("change", (e) => {
    state.pageSize = parseInt(e.target.value);
    state.currentPage = 1;
    renderTable();
  });

  searchInput.addEventListener("input", (e) => {
    state.searchTerm = e.target.value.toLowerCase();
    state.currentPage = 1;
    renderTable();
  });

  // Fetch Data
  try {
    const response = await authAPI.apiRequest("/users/history");
    if (response.success && response.data && response.data.events) {
      state.data = response.data.events;
      renderTable();
    } else {
      tableBody.innerHTML =
        '<tr><td colspan="9" style="text-align:center;">No data available.</td></tr>';
    }
  } catch (error) {
    console.error("Error fetching history:", error);
    tableBody.innerHTML =
      '<tr><td colspan="9" style="text-align:center;">Error loading data.</td></tr>';
  }

  function renderTable() {
    const filteredData = state.data.filter(
      (item) =>
        (item.event_name &&
          item.event_name.toLowerCase().includes(state.searchTerm)) ||
        (item.category &&
          item.category.toLowerCase().includes(state.searchTerm))
    );

    const totalItems = filteredData.length;
    const totalPages = Math.ceil(totalItems / state.pageSize);

    if (state.currentPage > totalPages) state.currentPage = totalPages || 1;
    if (state.currentPage < 1) state.currentPage = 1;

    const start = (state.currentPage - 1) * state.pageSize;
    const end = start + state.pageSize;
    const pageData = filteredData.slice(start, end);

    if (pageData.length === 0) {
      tableBody.innerHTML =
        '<tr><td colspan="9" style="text-align:center;">No matching records found.</td></tr>';
    } else {
      tableBody.innerHTML = pageData
        .map((item, index) => {
          const no = start + index + 1;
          let statusBadge = "";
          if (item.status === "validated") {
            statusBadge = '<span class="badge-success">Tervalidasi</span>';
          } else if (item.status === "processed") {
            statusBadge = '<span class="badge-processed">Diproses</span>';
          } else {
            statusBadge = item.status;
          }

          let tingkat = Number(item.date_issued.slice(-4));
          const userId = JSON.parse(localStorage.getItem("userIdentity"));
          tingkat = tingkat - Number(userId.angkatan) + 1;

          return `
        <tr>
          <td>${no}</td>
          <td>${item.event_name || "-"}</td>
          <td>${item.category || "-"}</td>
          <td>${item.tingkat || "-"}</td>
          <td>${item.date_issued || "-"}</td>
          <td>${item.skor_ai || "-"}</td>
          <td>${tingkat || "-"}</td>
          <td>${statusBadge}</td>
        </tr>
        `;
        })
        .join("");
    }

    renderPagination(totalPages);
  }

  function renderPagination(totalPages) {
    if (totalPages <= 1) {
      paginationControls.innerHTML = "";
      return;
    }

    let paginationHTML = `
      <button class="pagination-btn" ${
        state.currentPage === 1 ? "disabled" : ""
      } data-page="${state.currentPage - 1}">Prev</button>
    `;

    for (let i = 1; i <= totalPages; i++) {
      if (
        i === 1 ||
        i === totalPages ||
        (i >= state.currentPage - 1 && i <= state.currentPage + 1)
      ) {
        paginationHTML += `<button class="pagination-btn ${
          i === state.currentPage ? "active" : ""
        }" data-page="${i}">${i}</button>`;
      } else if (i === state.currentPage - 2 || i === state.currentPage + 2) {
        paginationHTML += `<span>...</span>`;
      }
    }

    paginationHTML += `
      <button class="pagination-btn" ${
        state.currentPage === totalPages ? "disabled" : ""
      } data-page="${state.currentPage + 1}">Next</button>
    `;

    paginationControls.innerHTML = paginationHTML;

    paginationControls.querySelectorAll(".pagination-btn").forEach((btn) => {
      btn.addEventListener("click", () => {
        if (!btn.disabled && !btn.classList.contains("active")) {
          state.currentPage = parseInt(btn.dataset.page);
          renderTable();
        }
      });
    });
  }
}
